CREATE TABLE IF NOT EXISTS EQUATIONS_ROOTS
(
    EQUATION_ID int NOT NULL,
    ROOT_ID int NOT NULL,

);

ALTER TABLE EQUATIONS_ROOTS
ADD CONSTRAINT fk_eq
FOREIGN KEY ID
REFERENCES EQUATIONS_ROOTS(EQUATION_ID);

ALTER TABLE EQUATIONS_ROOTS
ADD CONSTRAINT fk_roots
FOREIGN KEY ID
REFERENCES EQUATIONS_ROOTS(ROOT_ID);