CREATE TABLE IF NOT EXISTS EQUATIONS_ROOTS
(
    EQUATION_ID int NOT NULL,
    ROOT_ID int NOT NULL

);

ALTER TABLE EQUATIONS_ROOTS
ADD CONSTRAINT fk_eq_id
FOREIGN KEY (EQUATION_ID)
REFERENCES EQUATIONS(ID);

ALTER TABLE EQUATIONS_ROOTS
ADD CONSTRAINT fk_roots_id
FOREIGN KEY (ROOT_ID)
REFERENCES ROOTS(ID);